url: "" # the base hostname & protocol for your site, e.g. http://example.com
baseurl: "" # the subpath of your site, e.g. /blog
title: "Lorenzo Riva" # the name of your site, e.g. ACME Corp.
description: "Second-year graduate student in mathematics at the University of Notre Dame."
