# Top menu, both current and future tabs
# format: - {name: 'Name', url: '/url'}

menu:
- {name: 'Publications', url: '/publications'}
- {name: 'Notes', url: '/misc'}
- {name: 'Seminar', url: '/seminar'}

future_menu:
- {name: 'Origami', url: '/origami'}
- {name: 'Research', url: '/research'}
- {name: 'Teaching', url: '/teaching'}
